services:
  voip-balance-notification:
    container_name: voip-balance-notification
    image: vit100/voip-balance-notification
    restart: unless-stopped
    build:
      context: .
    environment:
      NODE_ENV: production
      BASE_URL: ${BASE_URL}
      BEARER_TOKEN: ${BEARER_TOKEN}
      API_USERNAME: ${API_USERNAME}
      API_PASSWORD: ${API_PASSWORD}
      SENDGRID_KEY: ${SENDGRID_KEY}
      SENDGRID_TEMPLATEID: ${SENDGRID_TEMPLATEID}
      SEND_FROM_EMAIL: ${SEND_FROM_EMAIL}
      SEND_FROM_NAME: ${SEND_FROM_NAME}
      SEND_BCC: ${SEND_BCC}
      CRON_SCHEDULE: ${CRON_SCHEDULE}